version: 2.1
jobs:
  my-job:
    docker:
      - image: cimg/base:2021.04
    steps:
      - run: |
          pwd
          ls -l
          docker-compose build

workflows:
  say-hello-workflow:
    jobs:
      - my-job
