version: 2.1
jobs:
  my-job:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Docker Compose
          environment:
            COMPOSE_VERSION: 'v2.1.1'
          command: |
            curl -L "https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - run: |
          docker-compose --version
          docker-compose build
          docker-compose up -d
          sleep 2
          docker-compose logs

workflows:
  say-hello-workflow:
    jobs:
      - my-job
