version: 2.1
jobs:
  my-job:
    docker:
      - image: alpine
    steps:
      - run: |
          echo 'hello world'
          echo 'there'

workflows:
  say-hello-workflow:
    jobs:
      - my-job
